### ISSUE TITLE
balise FOREIGN à traiter

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS-LACITO/eastlingplayer#16]
Affichage en italique ?

`        <FORM kindOf="phono">aː̃ki yiknoŋ <FOREIGN xml:lang="ne">bhālu</FOREIGN>-ha dusi dzaːkom ɩxtse.</FORM>
`

Exemple : 
corpus/show?oai_primary=cocoon-b780e400-fff4-3c5c-9f42-d21b674a5060&oai_secondary=cocoon-7bada1f0-4742-30ef-93b4-58ab3c40f47a&optionWords=true&optionNotes=true&optionTranscriptions=%2Bphono&optionTranslations=%2Ben%2Bfr&optionGlosses=&optionWholeTranscriptions=false&optionWholeTranslations=

**Comment by m8nli9ht** [comment]
vu, mettre une classe CSS "foreign"

**Comment by alexis-michaud** [comment]
Il y a aussi les mots encodés comme emprunts avec un autre format, et affichés en italiques : 

"Mots en italique = Mots des langues de contact"

Exemple ici : 
https://doi.org/10.24397/pangloss-0000299

```
            <M class="CL">
                <FORM>bakˈratʃ</FORM>
                <TRANSL xml:lang="en">bowl.SG.M (mult)</TRANSL>
            </M>
```

**Comment by m8nli9ht** [comment]
Besoin de précisions (à rediscuter en live) : dans ce texte, je trouve une balise FOREIGN dans la balise FORM d'une phrase mais étrangement elle ne contient qu'un mot alors que la traduction est bien plus longue ...erreur de saisie dans ce document ?

**Comment by alexis-michaud** [comment]
"ce texte" = quel texte ? Dans celui cité plus haut ([https://doi.org/10.24397/pangloss-0000299](https://doi.org/10.24397/pangloss-0000299), crdo-MKD_CHAMPS), je ne vois pas de balise FOREIGN

**Comment by m8nli9ht** [comment]
> 
> 
> "ce texte" = quel texte ? Dans celui cité plus haut (https://doi.org/10.24397/pangloss-0000299, crdo-MKD_CHAMPS), je ne vois pas de balise FOREIGN

celui-ci :
oai_primary=cocoon-b780e400-fff4-3c5c-9f42-d21b674a5060&oai_secondary=cocoon-7bada1f0-4742-30ef-93b4-58ab3c40f47a

dans la première phrase, voilà ce qu'on trouve : 
![image](https://user-images.githubusercontent.com/6407776/100284291-4460c500-2f6f-11eb-87a5-98971e607c23.png)

**Comment by alexis-michaud** [comment]
Oui, je vois : 

```
    <S id="HAYUAs1" who="narrator" xml:lang="x-sil-vay">
        <AUDIO start="1.1803" end="6.4712"/>
        <FORM kindOf="phono">aː̃ki yiknoŋ <FOREIGN xml:lang="ne">bhālu</FOREIGN>-ha dusi dzaːkom ɩxtse.</FORM>
        <TRANSL xml:lang="en">They say that a bear ate the bajra-millet in our field.</TRANSL>
        <TRANSL xml:lang="fr">On dit qu'un ours mangeait le millet dans nos champs.</TRANSL>
```

Dans cet exemple (langue : hayu), le fait qu'un mot soit un emprunt (en l'espèce, un emprunt à la langue népali, langue nationale) est encodé par une balise `<FOREIGN xml:lang="ne">bhālu</FOREIGN>` qui se trouve à l'intérieur d'une balise `<FORM kindOf="phono">` : la transcription de la phrase. C'est une façon de coder bien différente de celle de l'autre exemple (langue : nashta). 

Ce n'est pas une erreur de saisie, c'est un choix fait par le déposant. 

Dans cette façon de faire, l'info est codée deux fois : 

- une fois au niveau de la forme de la phrase entière, en entourant les mots d'emprunt d'une balise FOREIGN
- et une fois dans les gloses au niveau du morphème, en mettant un attribut "langue" particulier aux mots d'emprunt : en l'occurrence, l'attribut "ne" (langue : népali). Exemple : ligne 28

```
           <M xml:lang="ne" class="misc">
                <FORM kindOf="phono">bhālu</FORM>
            </M>
```

C'est un peu compliqué. Pour le lecteur : que diriez-vous, lorsqu'il y a une balise FOREIGN dans la forme d'un élément (phrase, mot, morphème...) de lui mettre une classe / lui poser un attribut "mise en valeur" (sorte de `<em>`, dans une logique HTML), qui serait ensuite mis en italiques ou gras ou couleur ou toute autre forme de mise en valeur dans la feuille de style appliquée sur le site web ? (question d'intégration)

**Comment by alexis-michaud** [comment]
@m8nli9ht @sguillaume ça serait bien de reprendre cette question. On se calerait un rendez-vous pour en parler ?
@sguillaume pour le choix de recommandations aux déposant·e·s, et pour faire connaître clairement les fonctionnalités qu'offre Pangloss pour les phénomènes de langues en contact : problématique super-importante pour les sciences du langage
@m8nli9ht pour la mise en oeuvre, aussi pour l'éditeur Eastling : pour l'encodage de phénomènes de changement de langue ("code-switching") et d'emprunts à d'autres langues.

**Comment by alexis-michaud** [comment]
Hello, un petit 'bis' juste pour redemander où on en est pour cette question ?

**Comment by m8nli9ht** [comment]
j'attendais qu'on en parle (pour reprendre le commentaire précédent!)

**Comment by m8nli9ht** [comment]
le mise en forme des éléments qu'on trouve dans les balises FOREIGN se fait-elle également au niveau de la concaténation de transcription de tout le texte ?

**Comment by m8nli9ht** [comment]
Traité. J'ai créé une balise <foreign> qu'il faudra mettre en forme dans le CSS (suite pour @Edouard)

**Comment by alexis-michaud** [comment]
Ah OK ! J'étais en train d'écrire des tartines. Ci-dessous pour mémoire.

En effet, quand on affiche la transcription du texte entier, ça serait super de mettre en valeur les mots d'emprunt qui sont encodés comme tels (de même que dans l'affichage phrase à phrase). Cela serait bienvenu et encouragerait en outre la généralisation de l'encodage des emprunts en mode 'texte structuré logiquement' (plutôt que par des conventions implicites, non lisibles directement par un script informatique).

Ca touche à une question plus générale qui est le contenu des éléments : est-ce qu'on met de la mise en forme dedans. À l'heure actuelle, le contenu des éléments `<FORM>` (que ce soit pour `<M>`, `<W>`, `<S>`, ou `<TEXT>` ou  `<WORDLIST>`) est généralement en texte simple, sans indications de mise en forme (italiques, gras, petites capitales, etc.). L'emploi de la balise `<FOREIGN>` à l'intérieur d'un élément `<FORM>` a pour résultat que le contenu de cet élément n'est pas juste du texte simple. 
- faut-il recommander la généralisation de ce type d'encodage ?
- faut-il au contraire 'résorber' ces pratiques / les décourager, afin que le XML puisse être 'dépiauté' aisément, en prélevant le contenu entre balises `<FORM>` sans avoir besoin de prendre 36 précautions pour le maniement de ce contenu ? 

Pour le cas spécifique de l'élément `<FOREIGN>`, il est dit dans la [définition du format (DTD)](https://cocoon.huma-num.fr/exist/crdo/meta/cocoon-49aefa90-8c1f-3ba8-a099-0ebefc6a2aa7) que c'est déconseillé, semble-t-il. @sguillaume tu confirmes ?
```
<!-- for loanwords (deprecated) -->
<!ELEMENT FOREIGN	(#PCDATA)				>
```

Pour mémoire : dans bien des cas, les balises `<FORM>` contiennent d'ores et déjà autre chose qu'une simple suite de phonèmes. Il y a de la ponctuation, des éléments **<ajoutés>** **[ou retranchés]**, bref, des infos qui pourraient être recodées différemment mais qui ont vraisemblablement vocation à rester dans l'élément `<FORM>`. Même si on les en retirait, par exemple pour les mettre dans des éléments `<NOTE>`, il faudrait bien établir un lien avec l'emplacement concerné au sein de l'élément `<FORM>`, et pour ça avoir une sorte d'appel de note. Du coup le traitement de la balise dont il est question ici a du sens, aussi dans une perspective 'générique', pour la gestion (potentiellement) d'autres types d'infos.
