### ISSUE TITLE
souci d'affichage via DOI : alignement <S> seulement à la 2e tentative

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS-LACITO/eastlingplayer#71]
Souci d'affichage quand on clique sur un DOI qui comprend un ancrage au 1er niveau de granularité. Exemple : 

https://doi.org/10.24397/pangloss-0005673#S37

L'affichage doit se faire en alignant verticalement sur la phrase 9. 

Sur Chrome (sysème Ubuntu) : l'alignement \<S\> se fait seulement à la 2e tentative.
À la première tentative : l'alignement se fait sur le début du document, comme si on n'avait pas passé d'info de numéro de phrase.
Si on [recharge](https://pangloss.cnrs.fr/corpus/show?lang=en&mode=pro&oai_primary=cocoon-6cfea344-ef3f-4964-b6ec-871efe6d77df&oai_secondary=cocoon-b976f9db-f0fd-463d-b2d4-7c58366005b9&optionTextTranscriptions=&optionTextTranslations=&optionSentenceTranscriptions=phono&optionSentenceTranslations=fr&optionWordTranscriptions=phono&optionWordTranslations=fr&optionMorphemeTranscriptions=&optionMorphemeTranslations=&optionNotes=&continuousPlay=false) : même souci.
En revanche, si après la première tentative on ouvre le même DOI dans un autre onglet, l'alignement se fait.

Cela rappelle un bogue ancien et résolu : 
https://github.com/CNRS-LACITO/Pangloss/issues/141

**Comment by m8nli9ht** [comment]
Je pense que c'est un ticket pour Pangloss, en effet le lecteur ne propose que le lien DOI mais ne gère pas sa redirection vers l'URL Pangloss
